# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ejectdrive.com
email: deeschaedler@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A micro-blog to document my journey through life, adulthood, and IT.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ejectdrive.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-remote-theme
  - jekyll-feed
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/DSchaedler"
    - title: Site Source
      icon: github
      url: "https://github.com/DSchaedler/DSchaedler.github.io"  
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/dschaedler"
    - title: Bluesky
      icon: bluesky
      url: "https://bsky.app/profile/ejectdrive.com"
    - title: Hive
      icon: hive
      url: "https://hive.blog/@queenmeteor"
    - title: Nostr
      icon: creative-commons-by
      url: "https://njump.me/nprofile1qqsxcqfcjukppq6j8fvtawm7ujr7yt7sseajclf5jfqxk5xtf2q578gpzpmhxue69uhkummnw3ezumt0d5hszrnhwden5te0dehhxtnvdakz7qgawaehxw309ahx7um5wghxy6t5vdhkjmn9wgh8xmmrd9skctcu2060y"
  nav_pages:
    - latest.md
    - technology.md
    - personal.md
    - about.md
    - other.md
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
